refactor(hours request): add scholarship request endpoints
unadecaisc/strix-api pull request #33
Opened 2024-07-17 00:17 UTC by JakecorralesCespedes

2024-07-17 16:04 UTC, wmartzh commented on src/scholarship-request/dto/create-scholarship-request.dto.ts
> +``
Remove this

2024-07-17 16:05 UTC, wmartzh requested changes
Please make sure to run the `npm run format`

2024-07-18 20:34 UTC, wmartzh commented on src/scholarship-request/scholarship-request.service.ts
> +      return this.prismaService.studentOnDepartment.create({
Please validate that the student and department exist before create

2024-07-18 21:06 UTC, JakecorralesCespedes commented on src/scholarship-request/dto/create-scholarship-request.dto.ts
> +``
line 14?? or from line 11 to 14??

2024-07-21 22:01 UTC, closed without merging